---
title: "Association Rules"
author: "Margherita Berutti"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(arules)
library(arulesViz)
library(FactoMineR)
library(tidyverse)
source("settings.R")
```

Reading the data. 

```{r}
train <- read.csv(file.path(path_intermediate, "train_imputed.csv"))
```


```{r}
train <- train[,-1]

train_discretized <- train

train_discretized$instrumentalness <- ifelse(
  train$instrumentalness > 0.5, 
  "Instrumental", 
  "Vocal"
)
train_discretized$instrumentalness <- as.factor(train_discretized$instrumentalness)

categorical_cols <- c("key", "audio_mode", "time_signature", "instrumentalness")

#numerical columns to discretise with "frequency" crit (each category has the same number of elements)
freq_cols <- c("liveness", "acousticness", "speechiness", "song_duration_ms")
#numerical columns to discretise with "intervals" (the intervals has the same dimension)
interval_cols <- c("loudness", "danceability", "audio_valence", "energy", "tempo", "song_popularity")

train_discretized[freq_cols] <- lapply(train[freq_cols], function(col) {
  discretize(col, method = "frequency", breaks = 3, labels = c("Low", "Medium", "High"))
})

train_discretized[interval_cols] <- lapply(train[interval_cols], function(col) {
  discretize(col, method = "interval", breaks = 3, labels = c("Low", "Medium", "High"))
})

train_discretized[categorical_cols] <- lapply(train[categorical_cols], as.factor)

```

```{r}
train_transactions <- as(train_discretized, "transactions")

# in order to decide minimum support
itemFrequencyPlot(train_transactions, topN = 20, type = "relative")
```

```{r}
# but i am interested in rules containing the song_popularity as rhs so i want to know the support of song popularity

all_items <- itemLabels(train_transactions)

popularity_items <- grep("song_popularity=", all_items, value = TRUE)
popularity_transactions <- train_transactions[ , popularity_items]
popularity_freqs <- itemFrequency(popularity_transactions, type = "relative")

print("Frecuencias Relativas (Proporciones) para Popularidad:")
print(popularity_freqs)
```

```{r}
rules <- apriori(train_transactions, 
                 parameter = list(supp = 0.01, conf = 0.1, maxlen = 4))
rules_sorted <- sort(rules, by = "lift", decreasing = TRUE)

inspect(head(rules_sorted, 10))
```

```{r}
#now i want to inspect only rules that has song popularity in the rhs
rules_filtrado <- arules::subset(rules,
                                    subset = rhs %in% c("song_popularity=High", "song_popularity=Medium",
                                                 "song_popularity=Low") & lift > 1 & confidence > 0.7)
rules_filtrado <- sort(rules_filtrado, by = "support", decreasing = TRUE)

inspect(rules_filtrado[1:5])

rules_filtrado_high <- arules::subset(rules,
                                    subset = rhs %in% "song_popularity=High" & lift > 1)
rules_filtrado_high <- sort(rules_filtrado_high, by = "support", decreasing = TRUE)
inspect(rules_filtrado_high[1:5])


rules_filtrado_low <- arules::subset(rules,
                                    subset = rhs %in% "song_popularity=Low" & lift > 1)
rules_filtrado_low <- sort(rules_filtrado_low, by = "support", decreasing = TRUE)
inspect(rules_filtrado_low[1:5])
```



